# Generated by Django 5.2.8 on 2025-12-04 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(unique=True)),
                ('baikal_password', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(unique=True)),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalDAVConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('calendar_name', models.CharField(default='default', max_length=200)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Lecture seule'), ('write', 'Lecture/Écriture')], default='read', help_text="Niveau de permission pour l'utilisateur partagé", max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de calendrier',
                'verbose_name_plural': 'Partages de calendriers',
            },
        ),
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du calendrier', max_length=200)),
                ('calendar_url', models.URLField(help_text='URL du calendrier')),
                ('is_enabled', models.BooleanField(default=True, help_text='Afficher ce calendrier')),
                ('color', models.CharField(default='#005f82', help_text="Couleur d'affichage", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caldav_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='api.caldavconfig')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Utilisateurs avec qui ce calendrier est partagé', related_name='shared_calendars', through='api.CalendarShare', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'calendar_url')},
            },
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='calendar_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calendarsource'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caldav_uid', models.CharField(blank=True, help_text="UID de l'événement CalDAV", max_length=500, null=True, unique=True)),
                ('caldav_etag', models.CharField(blank=True, help_text="ETag de l'événement CalDAV", max_length=200, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('calendar_source', models.ForeignKey(blank=True, help_text='Calendrier source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.calendarsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='calendarshare',
            unique_together={('calendar_source', 'user')},
        ),
    ]
