# Generated by Django 5.2.8 on 2025-11-21 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='caldav_etag',
            field=models.CharField(blank=True, help_text="ETag de l'événement CalDAV", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='caldav_uid',
            field=models.CharField(blank=True, help_text="UID de l'événement CalDAV", max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CalDAVConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caldav_url', models.URLField(help_text='URL du serveur CalDAV (ex: https://example.com/baikal/dav.php)')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('calendar_name', models.CharField(default='default', max_length=200)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caldav_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
