# Generated by Django 5.2.8 on 2025-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsource',
            name='caldav_config',
        ),
        migrations.AddField(
            model_name='user',
            name='calendar_name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.DeleteModel(
            name='CalDAVConfig',
        ),
    ]
