# Generated by Django 5.2.8 on 2025-12-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_calendarsource_caldav_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaikalCalendar',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('synctoken', models.IntegerField(db_column='synctoken')),
                ('components', models.BinaryField(blank=True, db_column='components', max_length=255, null=True)),
                ('is_visible', models.BooleanField(db_column='is_visible', default=True)),
            ],
            options={
                'db_table': 'calendars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaikalCalendarInstance',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('calendarid', models.IntegerField(db_column='calendarid')),
                ('principaluri', models.BinaryField(blank=True, db_column='principaluri', max_length=255, null=True)),
                ('access', models.IntegerField(db_column='access')),
                ('displayname', models.CharField(blank=True, db_column='displayname', max_length=100, null=True)),
                ('uri', models.BinaryField(blank=True, db_column='uri', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('calendarorder', models.IntegerField(db_column='calendarorder')),
                ('calendarcolor', models.BinaryField(blank=True, db_column='calendarcolor', max_length=255, null=True)),
                ('timezone', models.TextField(blank=True, db_column='timezone', null=True)),
                ('transparent', models.BooleanField(db_column='transparent', default=False)),
                ('share_href', models.CharField(blank=True, db_column='share_href', max_length=255, null=True)),
                ('share_displayname', models.CharField(blank=True, db_column='share_displayname', max_length=100, null=True)),
                ('share_invitestatus', models.BooleanField(db_column='share_invitestatus', default=False)),
                ('display', models.BooleanField(db_column='display', default=True)),
                ('defined_name', models.CharField(blank=True, db_column='defined_name', max_length=100, null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
            ],
            options={
                'db_table': 'calendarinstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaikalCalendarObject',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('calendardata', models.BinaryField(blank=True, db_column='calendardata', null=True)),
                ('uri', models.BinaryField(blank=True, db_column='uri', max_length=255, null=True)),
                ('calendarid', models.IntegerField(db_column='calendarid')),
                ('lastmodified', models.IntegerField(blank=True, db_column='lastmodified', null=True)),
                ('etag', models.BinaryField(blank=True, db_column='etag', max_length=255, null=True)),
                ('size', models.IntegerField(db_column='size')),
                ('componenttype', models.BinaryField(blank=True, db_column='componenttype', max_length=255, null=True)),
                ('firstoccurence', models.IntegerField(blank=True, db_column='firstoccurence', null=True)),
                ('lastoccurence', models.IntegerField(blank=True, db_column='lastoccurence', null=True)),
                ('uid', models.BinaryField(blank=True, db_column='uid', max_length=255, null=True)),
                ('datesDeRecurrence', models.TextField(blank=True, db_column='datesDeRecurrence', null=True)),
            ],
            options={
                'db_table': 'calendarobjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaikalPrincipal',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('uri', models.BinaryField(db_column='uri', max_length=255, unique=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True)),
                ('displayname', models.CharField(blank=True, db_column='displayname', max_length=80, null=True)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
            ],
            options={
                'db_table': 'principals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaikalUser',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.BinaryField(db_column='username', max_length=255, unique=True)),
                ('digesta1', models.BinaryField(blank=True, db_column='digesta1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
