# Generated by Django 5.2.8 on 2025-11-23 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_caldav_etag_task_caldav_uid_task_last_synced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du calendrier', max_length=200)),
                ('calendar_url', models.URLField(help_text='URL du calendrier')),
                ('is_enabled', models.BooleanField(default=True, help_text='Afficher ce calendrier')),
                ('color', models.CharField(default='#005f82', help_text="Couleur d'affichage", max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caldav_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='api.caldavconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'calendar_url')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='calendar_source',
            field=models.ForeignKey(blank=True, help_text='Calendrier source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.calendarsource'),
        ),
    ]
