# Generated by Django 5.2.8 on 2025-11-25 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_calendarsource_task_calendar_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsource',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_calendars', to=settings.AUTH_USER_MODEL),
        ),
    ]
