# Generated by Django 5.2.8 on 2025-12-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_baikalcalendar_baikalcalendarinstance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsource',
            name='shared_with',
        ),
        migrations.AlterUniqueTogether(
            name='calendarsource',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='calendarsource',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='calendar_source',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalendarShare',
        ),
        migrations.DeleteModel(
            name='CalendarSource',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
