# Generated by Django 5.2.8 on 2025-11-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calendarsource_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarsource',
            name='shared_with',
        ),
    ]
