# Generated by Django 5.2.8 on 2025-11-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_calendarsource_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Lecture seule'), ('write', 'Lecture/Écriture')], default='read', help_text="Niveau de permission pour l'utilisateur partagé", max_length=10)),
                ('calendar_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.calendarsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage de calendrier',
                'verbose_name_plural': 'Partages de calendriers',
                'unique_together': {('calendar_source', 'user')},
            },
        ),
        migrations.AddField(
            model_name='calendarsource',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs avec qui ce calendrier est partagé', related_name='shared_calendars', through='api.CalendarShare', to=settings.AUTH_USER_MODEL),
        ),
    ]
