# Generated by Django 5.2.8 on 2025-11-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_calendarshare_calendarsource_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caldavconfig',
            name='caldav_url',
        ),
    ]
